Translate/Update Translate curl-multi-strerror.xml
php/doc-pt_br pull request #207
Opened 2022-11-30 12:13 UTC by resolvendobug

Atualização e Tradução do arquivo curl-multi-strerror.xml para pt-BR

2022-11-30 20:39 UTC, MauricioFauth requested changes
Faltou essa alteração:
https://github.com/php/doc-en/commit/73fae4ee51b644b72028e610abefefced57c18ad#diff-7671bde3a43b5f6ae69a77751387d7d960b4701e2ec51a5aa8134a629d129b97

https://github.com/php/doc-en/blob/23cda460978ca25b9c0be003862095cd0eb20b00/reference/curl/functions/curl-multi-strerror.xml#L51

```diff
-$ch1 = curl_init("http://example.com"/);
+$ch1 = curl_init("http://example.com/");
```

2022-11-30 20:39 UTC, MauricioFauth commented on reference/curl/functions/curl-multi-strerror.xml
> +    // Exibir mensagem de erro
```suggestion
    // Exibe mensagem de erro
```

2022-11-30 20:39 UTC, MauricioFauth commented on reference/curl/functions/curl-multi-strerror.xml
> +// Verifique se há erros
```suggestion
// Verifica se há erros
```

2022-12-01 01:11 UTC, resolvendobug commented
Eu atualizei as sugestoes e as correçoes apontadas

2022-12-01 01:19 UTC, alfsb commented
> Eu atualizei as sugestoes e as correçoes apontadas

Opa, muito boas as suas traduções e atualizações. Escrevendo para avisar que talvez demore um pouco para conseguir subir esse PR, dado que o manual acabou "quebrando" recentemente. O seu PR está tranquilo, a quebra foi em outra parte, que não tem muito a ver.

Até, aproveitando o movimento, eu não sei se vou conseguir parar para ver isso tão cedo, mas é basicamente equalizar ou retraduzir `/language/oop5/` e `/language/types/` até o manual voltar a compilar. Capaz de isso, por sua vez, quebrar outras partes, o que daí exige de fazer mexidas em cascata, e daí a razão porque essa situação acaba demorando para resolver.

2022-12-01 01:46 UTC, resolvendobug commented
Obrigado pelo retorno , espero que consiga resolver logo e que nao cause mais quebras em cascatas...  
boa sorte..  tenha uma otima noite.

2022-12-02 16:57 UTC, merged

2022-12-02 16:58 UTC, alfsb commented
Mudança de planos. Pequenas alterações assim, que consiga-se validar no olho que são consistentes, eu vou tentar subir, mesmo com o manual quebrado.