Partial translation to pt-br.
php/doc-pt_br pull request #4
Opened 2021-02-19 14:46 UTC by rafaelmamorim

2021-02-24 13:39 UTC, supercid requested changes

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +      <code>assert.exception=0</code> pode ser definida nas configurações INI.
```suggestion
      <code>assert.exception=0</code> pode ser definido nas configurações INI.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +      método <link linkend="object.construct">__construct()</link> deve ser utilizado.
```suggestion
	  Métodos com o mesmo nome de classe não são mais interpretados como construtor. O 
      método <link linkend="object.construct">__construct()</link> deve ser utilizado em seu lugar.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +	  terceiro argumento para a função <function>define</function> pode não ser mais &true;.
```suggestion
	  terceiro argumento para a função <function>define</function> não pode ser mais &true;.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +      removida. A função <function>spl_autoload_register</function> deve ser utilizada.
```suggestion
      removida. A função <function>spl_autoload_register</function> deve ser utilizada em seu lugar.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +      devem ser utilizados.
```suggestion
      devem ser utilizados em seu lugar.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +	  Foi removida a capacidade de desvincular <varname>this</varname> de encerramentos que foram
```suggestion
	  Foi removida a capacidade de desvincular <varname>this</varname> de closures que foram 
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +      A habilidade de desvincular <varname> this </varname> de fechamentos apropriados que contêm usos de
```suggestion
      A habilidade de desvincular <varname>this</varname> de closures que contêm usos de
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +      A habilidade de utilizar <function>array_key_exists</function> com objetos foi removidawith objects has been removed.
```suggestion
      A habilidade de utilizar <function>array_key_exists</function> com objetos foi removida.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +	  array/objeto lançam um <classname> TypeError </classname>.
```suggestion
      O comportamento da função <function>array_key_exists</function> com relação ao tipo do parâmetro
      <parameter>key</parameter> agora é consistente com a função <function>isset</function> e 
      acesso normal à array. Todos os tipos de chave agora usam as coerções usuais e as chaves de 
	  array/objeto lançam um <classname>TypeError</classname>.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +      O nível de error_reporting padrão é <constant>E_ALL</constant>. Anteriormente excluído
```suggestion
      O nível de error_reporting padrão é <constant>E_ALL</constant>. Anteriormente excluía
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +	  erros.
```suggestion
	  Adicionalmente, cuidados devem ser tomados para que mensagens de erro não sejam mostradas 
	  no ambiente de produção, o que podem resultar em vazamento de informações. Certifique-se 
	  de que a diretiva <code>display_errors=Off</code> seja usada em conjunto com o log de 
	  erros.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +      <literal>#[</literal> não é mais interpretado como o início de um comentário is no longer interpreted as the start of a comment,
```suggestion
      <literal>#[</literal> não é mais interpretado como o início de um comentário,
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +       deve ser usado em seu lugar.
```suggestion
	  Argumentos com um valor padrão que avaliam para &null; em tempo de execução, não irão mais marcar o tipo do parâmetro como implícito. Um tipo explícito nulo, ou explicitamente &null; como argumento padrão
       deve ser usado em seu lugar.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +	  de encontro ao comportamento documentado.
```suggestion
      Os stream wrappers <literal>data://</literal>  não podem mais ser writable, indo 
	  de encontro ao comportamento documentado.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +      a operação de mesclagem de array com <literal>+</literal>, que permanece suportado.
```suggestion
      a operação de mesclagem de array com <literal>+</literal>, que permanece suportada.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +	  A conversão de float para string agora sempre terá o mesmo comportamento, independentemente do local.
Aqui ele está se referindo às localidades: https://www.php.net/manual/en/class.locale.php
```suggestion
	  A conversão de float para string agora sempre terá o mesmo comportamento, independentemente da localidade.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +      veja as funções <function>printf</function>, <function>number_format</function> and
```suggestion
      Veja as funções <function>printf</function>, <function>number_format</function> and
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +     tanto quanto um &resource;.
```suggestion
     ao invés de um &resource;.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +     tanto quanto um &resource;.
```suggestion
     ao invés de um &resource;.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +     tanto quanto um &resource;.
```suggestion
     ao invés de um &resource;.
```

2021-02-24 13:39 UTC, supercid commented on appendices/migration80/incompatible.xml
> +	 tanto quanto um &resource;.
```suggestion
	 ao invés de um &resource;.
```

2021-02-24 14:35 UTC, supercid approved these changes

2021-03-06 18:22 UTC, closed without merging

2021-03-06 18:26 UTC, alfsb commented
Olá @rafaelmamorim 

Super agradecido pelos commits. E desculpe a demora em aplicá-los.

Deu alguns alertas de espaço no final de linha. Se puder configurar o seu editor para removê-los no futuro, ajuda bastante.

Mas pode continuar no arquivo, com fé e força, até terminar. Lembrar também de se acrescentar na tag de revisão quando terminar!